apiVersion: v1
kind: Service
metadata:
  name: training-service
  labels:
    app: training-service
spec:
  selector:
    app: training-service
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP 