apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference
        image: gcr.io/PROJECT_ID/inference:latest   # replace later
        ports:
        - containerPort: 8080
        env:
        - name: MODEL_PATH
          value: /app/models/resnet_cifar10.pth
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
