name: training_service_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.2.1
  - pytorch=2.6.0
  - torchvision=0.21.0
  - cudatoolkit=11.8
  - pillow=10.2.0
  - numpy=1.26.4
  - pip:
    - fastapi==0.110.0
    - uvicorn==0.27.1
    - python-multipart==0.0.9
    - httpx==0.27.0
    - pydantic==2.6.4
    - prometheus-client==0.19.0
    - tenacity==8.2.3
    - pytest==8.0.2
    - python-dotenv==1.0.1 