name: CI/CD – inference_service

on:
  push:
    paths:
      - "services/inference_service/**"
      - ".github/workflows/**"
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # checkout repo
    - uses: actions/checkout@v4

    # ----  Test phase  ----
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install deps & run pytest
      working-directory: services/inference_service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest
        pytest -q tests

    # ----  Build phase  ----
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # If you use Docker Hub -------------
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_TOKEN }}
    - name: Build & push image
      uses: docker/build-push-action@v5
      with:
        context: services/inference_service
        push: true
        tags: docker.io/${{ secrets.DH_USERNAME }}/inference:${{ github.sha }}

    # If you use GCR instead -------------
    # - uses: google-github-actions/auth@v2
    #   with:
    #     credentials_json: ${{ secrets.GCP_SA_KEY }}
    # - name: Build & push to GCR
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: services/inference_service
    #     push: true
    #     tags: gcr.io/${{ secrets.GCP_PROJECT }}/inference:${{ github.sha }}
