name: CI/CD – api_gateway_service

on:
  push:
    paths:
      - "services/api_gateway_service/**"
      - ".github/workflows/api-gateway-service-ci-cd.yml"
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # checkout repo
    - uses: actions/checkout@v4

    # ----  Test phase  ----
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install deps & run pytest
      working-directory: services/api_gateway_service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-mock httpx python-multipart
        # Run pytest with the correct Python path
        PYTHONPATH=. pytest -q tests

    # ----  Build phase  ----
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Auth to GCP
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Configure docker for GCR
    - name: Configure docker for Artifact/GCR
      run: gcloud auth configure-docker --quiet

    # Build & push to GCR
    - uses: docker/build-push-action@v5
      with:
        context: services/api_gateway_service
        push: true
        tags: gcr.io/${{ secrets.GCP_PROJECT }}/api-gateway:${{ github.sha }}

    # GKE deployment
    - name: Setup GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: YOUR_CLUSTER_NAME
        location: YOUR_CLUSTER_LOCATION
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Deploy to GKE
      run: |
        # Update deployment.yaml with the specific image we just built
        sed -i "s|gcr.io/PROJECT_ID/api-gateway:latest|gcr.io/${{ secrets.GCP_PROJECT }}/api-gateway:${{ github.sha }}|g" services/api_gateway_service/k8s/deployment.yaml
        
        # Apply Kubernetes configurations
        kubectl apply -f services/api_gateway_service/k8s/deployment.yaml
        kubectl apply -f services/api_gateway_service/k8s/service.yaml
        
        # Wait for deployment to roll out
        kubectl rollout status deployment/api-gateway 